/* eslint-disable @next/next/no-img-element */
/* eslint-disable react/no-unescaped-entities */
import Head from "next/head";
import Link from 'next/link';
import { Swiper, SwiperSlide } from "swiper/react";
import { Navigation, Autoplay } from "swiper/modules";
import 'swiper/css/bundle';
import 'animate.css';
export default function Home() {
  return (
    <>
      <Head>
        <title>Angel Pbx </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main">
        <section className="homeBanner">
          <div className="container">
            <div className="row">
              <div className="col-xl-6 col-lg-6 col-md-6  col-sm-7 col-12 my-auto animate__backInLeft" >
                <div className="content " >
                  <h1>
                    Redefining Business Communication : <span>  AI PBX </span>{" "}
                  </h1>
                  <p>
                    Your contact center and communications solution to keep
                    customers happy, agents engaged, and employees connected.
                  </p>
                  <a href="#industries" className="specialLearn">
                    Learn More
                  </a>
                </div>
              </div>
              <div className="col-xl-6 col-lg-6 col-md-6  mb-md-4 col-sm-5 col-12 my-auto">
                <div className="svgWrapper">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    x="0px"
                    y="0px"
                    viewBox="0 0 288 288"
                  >
                    <linearGradient
                      id="PSgrad_0"
                      x1="70.711%"
                      x2="0%"
                      y1="70.711%"
                      y2="0%"
                    >
                      <stop offset="0%" stopColor="#871fff" stopOpacity={1} />
                      <stop offset="100%" stopColor="#7ec9f4" stopOpacity={1} />
                    </linearGradient>
                    <path fill="url(#PSgrad_0)">
                      <animate
                        repeatCount="indefinite"
                        attributeName="d"
                        dur="10s"
                        values="M37.5,186c-12.1-10.5-11.8-32.3-7.2-46.7c4.8-15,13.1-17.8,30.1-36.7C91,68.8,83.5,56.7,103.4,45 c22.2-13.1,51.1-9.5,69.6-1.6c18.1,7.8,15.7,15.3,43.3,33.2c28.8,18.8,37.2,14.3,46.7,27.9c15.6,22.3,6.4,53.3,4.4,60.2 c-3.3,11.2-7.1,23.9-18.5,32c-16.3,11.5-29.5,0.7-48.6,11c-16.2,8.7-12.6,19.7-28.2,33.2c-22.7,19.7-63.8,25.7-79.9,9.7 c-15.2-15.1,0.3-41.7-16.6-54.9C63,186,49.7,196.7,37.5,186z; M51,171.3c-6.1-17.7-15.3-17.2-20.7-32c-8-21.9,0.7-54.6,20.7-67.1c19.5-12.3,32.8,5.5,67.7-3.4C145.2,62,145,49.9,173,43.4 c12-2.8,41.4-9.6,60.2,6.6c19,16.4,16.7,47.5,16,57.7c-1.7,22.8-10.3,25.5-9.4,46.4c1,22.5,11.2,25.8,9.1,42.6 c-2.2,17.6-16.3,37.5-33.5,40.8c-22,4.1-29.4-22.4-54.9-22.6c-31-0.2-40.8,39-68.3,35.7c-17.3-2-32.2-19.8-37.3-34.8 C48.9,198.6,57.8,191,51,171.3z; M37.5,186c-12.1-10.5-11.8-32.3-7.2-46.7c4.8-15,13.1-17.8,30.1-36.7C91,68.8,83.5,56.7,103.4,45 c22.2-13.1,51.1-9.5,69.6-1.6c18.1,7.8,15.7,15.3,43.3,33.2c28.8,18.8,37.2,14.3,46.7,27.9c15.6,22.3,6.4,53.3,4.4,60.2 c-3.3,11.2-7.1,23.9-18.5,32c-16.3,11.5-29.5,0.7-48.6,11c-16.2,8.7-12.6,19.7-28.2,33.2c-22.7,19.7-63.8,25.7-79.9,9.7 c-15.2-15.1,0.3-41.7-16.6-54.9C63,186,49.7,196.7,37.5,186z	"
                      />
                    </path>
                  </svg>
                  <div className="imgWrapper">
                    <img
                      src="https://ik.imagekit.io/8x8/v3/assets/blte621f0a2bd0e9f69/blt13d19ae559fe6ab9/661419a6fffe40533a1e32c5/_8x8-home-hero-.png?cache=82b5adfa44d12d2f4cbeefe287c4302c&tr=fo-auto,q-70,w-1200"
                      alt="img"
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="miniServices">
          <div className="container">
            <div className="row">
              <div className="col-xl-3 col-md-6 col-12">
                <div className="content">
                  <div className="iconWrapper">
                    <i className="fa-sharp fa-regular fa-globe" />
                  </div>
                  <h5>100,000+</h5>
                  <p>businesses choose Us, worldwide</p>
                </div>
              </div>
              <div className="col-xl-3 col-md-6 col-12">
                <div className="content">
                  <div className="iconWrapper">
                    <i className="fa-regular fa-code" />
                  </div>
                  <h5>1.15 million+</h5>
                  <p>lines of code to ensure utmost security</p>
                </div>
              </div>
              <div className="col-xl-3 col-md-6 col-12">
                <div className="content">
                  <div className="iconWrapper">
                    <i className="fa-sharp fa-regular fa-server" />
                  </div>
                  <h5>99.999%</h5>
                  <p>uptime reliability*</p>
                </div>
              </div>
              <div className="col-xl-3 col-md-6 col-12">
                <div className="content">
                  <div className="iconWrapper">
                    <i className="fa-sharp fa-regular fa-database" />
                  </div>
                  <h5>25 billion</h5>
                  <p>minutes &amp; messages terminated yearly</p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="industries pb-4 mt-4" id="industries">
          <div className="container">
            <div className="row">
              <div className="col-xl-10 mx-auto sectionHeading text-center">
                <h1>
                  Our AI-powered communications solutions for every industry
                </h1>
              </div>

            </div>

            <div className="row">
              <div className="col-xl-10  mx-auto">
                <ul className="nav nav-pills" id="pills-tab" role="tablist">
                  <li className="nav-item" role="presentation">
                    <button
                      className="nav-link active"
                      id="pills-home-tab"
                      data-bs-toggle="pill"
                      data-bs-target="#pills-home"
                      type="button"
                      role="tab"
                      aria-controls="pills-home"
                      aria-selected="true"
                    >
                      Hosted PBX
                    </button>
                  </li>
                  <li className="nav-item" role="presentation">
                    <button
                      className="nav-link"
                      id="pills-profile-tab"
                      data-bs-toggle="pill"
                      data-bs-target="#pills-profile"
                      type="button"
                      role="tab"
                      aria-controls="pills-profile"
                      aria-selected="false"
                    >
                      Call Center Solution
                    </button>
                  </li>
                  <li className="nav-item" role="presentation">
                    <button
                      className="nav-link"
                      id="pills-contact-tab"
                      data-bs-toggle="pill"
                      data-bs-target="#pills-contact"
                      type="button"
                      role="tab"
                      aria-controls="pills-contact"
                      aria-selected="false"
                    >
                      Toll Free Number
                    </button>
                  </li>
                  <li className="nav-item" role="presentation">
                    <button
                      className="nav-link"
                      id="pills-finance-tab"
                      data-bs-toggle="pill"
                      data-bs-target="#pills-finance"
                      type="button"
                      role="tab"
                      aria-controls="pills-finance"
                      aria-selected="false"
                    >
                      Local Number
                    </button>
                  </li>
                </ul>
              </div>
            </div>
            <div className="tab-content" id="pills-tabContent">
              <div
                className="tab-pane fade show active"
                id="pills-home"
                role="tabpanel"
                aria-labelledby="pills-home-tab"
                tabIndex={0}
              >
                <div className="row">
                  <div className="col-xl-6  col-lg-6 col-md-6 col-sm-12 col-12  my-auto">
                    <div className="imgWrapper">
                      <img
                        src="https://img.freepik.com/free-photo/portrait-young-handsome-business-man-thoughtful-male-dressed-blue-jeans-shirt-bearded-model-posing-office-near-paper-desk-speaking-phone_158538-17487.jpg"
                        alt=""
                      />
                    </div>
                  </div>
                  <div className="col-xl-6  col-lg-6 col-md-6 col-sm-12 col-12  my-auto">
                    <div className="content">
                      <h3>
                        Modernize Your Business Communications With Hosted PBX Solutions
                      </h3>
                      <div>
                        <Link href="/" className="specialLearn">
                          Learn More
                        </Link>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div
                className="tab-pane fade"
                id="pills-profile"
                role="tabpanel"
                aria-labelledby="pills-profile-tab"
                tabIndex={0}
              >
                <div className="row">
                  <div className="col-xl-6 my-auto">
                    <div className="imgWrapper">
                      <img
                        src="https://images.pexels.com/photos/7518718/pexels-photo-7518718.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
                        alt=""
                      />
                    </div>
                  </div>
                  <div className="col-xl-6 my-auto">
                    <div className="content">
                      <h3>
                        Why Angel PBX Serves Call Center Phone Systems best?
                      </h3>
                      <div>
                        <Link href="/" className="specialLearn">
                          Learn More
                        </Link>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div
                className="tab-pane fade"
                id="pills-contact"
                role="tabpanel"
                aria-labelledby="pills-contact-tab"
                tabIndex={0}
              >
                <div className="row">
                  <div className="col-xl-6 my-auto">
                    <div className="imgWrapper">
                      <img
                        src="https://images.pexels.com/photos/3789156/pexels-photo-3789156.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
                        alt=""
                      />
                    </div>
                  </div>
                  <div className="col-xl-6 my-auto">
                    <div className="content">
                      <h3>
                        What is
                        Toll Free Numbers & How Do They Work
                      </h3>
                      <div>
                        <Link href="/" className="specialLearn">
                          Learn More
                        </Link>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div
                className="tab-pane fade"
                id="pills-finance"
                role="tabpanel"
                aria-labelledby="pills-finance-tab"
                tabIndex={0}
              >
                <div className="row">
                  <div className="col-xl-6 my-auto">
                    <div className="imgWrapper">
                      <img
                        src="https://images.pexels.com/photos/3760612/pexels-photo-3760612.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
                        alt=""
                      />
                    </div>
                  </div>
                  <div className="col-xl-6 my-auto">
                    <div className="content">
                      <h3>
                        Our Unique Local Phone
                        Number
                      </h3>
                      <div>
                        <Link href="/" className="specialLearn">
                          Learn More
                        </Link>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="services">
          <div className="container">
            <div className="row mt-5 ">
              <div className="col-xl-4 mb-5 col-md-6 col-12">
                <div className="icon-phone">
                  <div className="a">
                    <div className="d-flex align-items-center justify-content-center">
                      <i className="fa-regular fa-sharp fa-phone-volume" />
                    </div>
                  </div>
                  <h5>Unified Communications</h5>
                  <div>
                    <p>
                      Allow the smooth transfer of communications to take place without any hassle, with our great services.
                    </p>
                  </div>
                  <a href="#industries" className="specialLearn">
                    Learn More
                  </a>
                </div>



              </div>
              <div className="col-xl-4 mb-5 col-md-6 col-12">
                <div className="icon-phone">
                  <div className="b">
                    <div className="d-flex align-items-center justify-content-center">
                      <i className="fa-solid fa-headset"></i>
                    </div>
                  </div>
                  <h5>Clear, Reliable and Resilient
                  </h5>
                  <div>
                    <p>
                      Develop the connectivity skill of your business with our team, to avail the reliable and resilient service, to heighten business communication.

                    </p>
                    <a href="#industries" className="specialLearn">
                      Learn More
                    </a>
                  </div>
                </div>
              </div>
              <div className="col-xl-4 mb-5 col-md-6 col-12">
                <div className="icon-phone">
                  <div className="c">
                    <div className="d-flex align-items-center justify-content-center">
                      <i class="fa-solid fa-mobile-screen-button"></i>
                    </div>
                  </div>
                  <h5>Clever Enterprise Effort
                  </h5>
                  <div>
                    <p>
                      Upgrade your business efficacy through better connectivity options in less time.

                    </p>
                  </div>
                  <a href="#industries" className="specialLearn">
                    Learn More
                  </a>
                </div>

              </div>

            </div>
            <div className="row mt-5 ">

              <div className="col-xl-4 mt-5 col-md-6 col-12">
                <div className="icon-phone">
                  <div className="d">
                    <div className="d-flex align-items-center justify-content-center">
                      <i className="fa-solid fa-globe"></i>
                    </div>
                  </div>
                  <h5>Network Security Services
                  </h5>
                  <div>
                    <p>
                      Using our hosted PBX services you can secure all your data and help your enterprise function without getting worried about any violation.
                    </p>
                  </div>
                  <a href="#industries" className="specialLearn">
                    Learn More
                  </a>
                </div>
              </div>
              <div className="col-xl-4 mt-5 col-md-6 col-12">
                <div className="icon-phone">
                  <div className="e">
                    <div className="d-flex align-items-center justify-content-center">
                      <i className="fa-solid fa-circle-nodes"></i>
                    </div>
                  </div>
                  <h5>Network & Call Quality Monitoring
                  </h5>
                  <div>
                    <p>
                      Using the features of our hosted PBX services, possess the feasible option of monitoring your call quality & network, to enhance better management facilities.

                    </p>
                  </div>
                  <a href="#industries" className="specialLearn">
                    Learn More
                  </a>
                </div>
              </div>
              <div className="col-xl-4 mt-5 col-md-6 col-12">
                <div className="icon-phone">
                  <div className="f">
                    <div className="d-flex align-items-center justify-content-center">
                      <i className="fa-solid fa-envelope-open-text"></i>
                    </div>
                  </div>
                  <h5>Unique Service & Support
                  </h5>
                  <div>
                    <p>
                      Feel free to reach out to our team of experts, to eradicate any type of the issues or discrepancies.

                    </p>
                  </div>
                  <a href="#industries" className="specialLearn">
                    Learn More
                  </a>
                </div>

              </div>
            </div>
          </div>
        </section>
        <section className="miniTesti">
          <div className="container">
            <div className="row">
              <div className="sectionHeading">
                <div className="col-xl-12 col-9">
                  <h1>
                    Trusted <span> by industry </span> leaders
                  </h1>
                </div>
              </div>
              <Swiper
                modules={[Navigation]}
                spaceBetween={50}
                slidesPerView={1}
                navigation
              >
                <SwiperSlide>
                  <div className="item">
                    <h3>
                      Get Unlimited Calling for $ 29.99 today!
                    </h3>
                    <p>
                      Upgrade your business communication today to make your brand more reliable and credible to your clients and leads. Connect better and spread further with our exclusive services. (Only USA & Canada)
                    </p>
                    <div className="d-flex mt-4">
                      <div className="imgWrapper">
                        <img
                          src="/assets/images/minitetsti1.webp"
                          alt="client"
                        />
                      </div>
                      <div className="miniContent ms-3 my-auto">
                        <h5>Angel Pbx </h5>
                        <p>Vice President, The Office</p>
                      </div>
                    </div>
                  </div>
                </SwiperSlide>
                <SwiperSlide>
                  <div className="item">
                    <h3>
                      Step up to the next-gen PBX telephony
                    </h3>
                    <p>Integrate your organization with the best hosted VoIP companies to work from anywhere, anytime. Enrich your business with superior communication and never miss a call!</p>
                    <div className="d-flex mt-4">
                      <div className="imgWrapper">
                        <img
                          src="/assets/images/minitesti2.webp"
                          alt="client"
                        />
                      </div>
                      <div className="miniContent ms-3 my-auto">
                        <h5>Angel Pbx </h5>
                        <p>Senior VP, The Office</p>
                      </div>
                    </div>
                  </div>
                </SwiperSlide>
              </Swiper>
            </div>
          </div>
        </section>
        {/*===Trusted partner section code start===*/}
        <section className="trusted_partnersection">
          <div className="container">
            <div className="row g-5">
              <div className="col-12">
                <div className="sectionHeading">
                  <h1>
                    {" "}
                    Trusted by <span> the best in the </span> business{" "}
                  </h1>
                </div>
              </div>
              <div className="col-xl-6 col-md-6 col-12">
                <div className="content_wraper">
                  <div className="left_box col-xl-5 col-12">
                    <img src="/assets/images/brand_logo1.svg" alt="brand_logo1" />
                  </div>
                  <div className="text_box col-xl-7 col-12">
                    <h3>UNLIMITED CALLING
                    </h3>
                    <p>
                      Whether you get an inbound, outbound, or blended call center setup, we serve you with unlimited calling facilities that enable steady operational flow.


                    </p>
                    <Link href="/" className="specialLearn mt-3">
                      {" "}
                      Explore the partnership{" "}
                    </Link>
                  </div>
                </div>
              </div>
              <div className="col-xl-6 col-md-6 col-12">
                <div className="content_wraper">
                  <div className="left_box blue col-xl-5 col-12">
                    <img src="/assets/images/brand_logo2.svg" alt="brand_logo1" />
                  </div>
                  <div className="text_box col-xl-7 col-12">
                    <h3>SAVE 60% ON AN AVERAGE
                    </h3>
                    <p>
                      Enjoy the benefit of 60% savings on your bills as you avail the classic services from the cloud call center solutions, with the cloud setting. Free yourself from the worry of installing any external hardware or phones.


                    </p>
                    <Link href="/" className="specialLearn">
                      {" "}
                      Explore the partnership{" "}
                    </Link>
                  </div>
                </div>
              </div>
              {/* <div class="col-12">
              <div class="our_brand">
                  <ul>
                      <li>
                          <h5>Travel</h5>
                      </li>
                      <li>
                          <h5>Finance</h5>
                      </li>
                      <li>
                          <h5>Retail</h5>
                      </li>
                      <li>
                          <h5>Healthcare</h5>
                      </li>
                      <li>
                          <h5>Telecom</h5>
                      </li>
                      <li>
                          <h5>Commerce</h5>
                      </li>
                  </ul>
              </div>
          </div> */}
            </div>
          </div>
        </section>
        {/*===End===*/}
        {/*===client review===*/}
        <section className="clientreview_section">
          <div className="container">
            <div className="row">
              <div className="col-12">
                <div className="sectionHeading">
                  <h1>
                    Featured <span> Client </span> Stories{" "}
                  </h1>
                </div>
              </div>
              <Swiper
                modules={[Autoplay]}
                spaceBetween={50}
                slidesPerView={3}
                autoplay
                loop
              >
                <SwiperSlide>
                  <div className="item">
                    <div className="review_box">
                      <div className="star_box">
                        <i className="fa-solid fa-star" />
                        <i className="fa-solid fa-star" />
                        <i className="fa-solid fa-star" />
                        <i className="fa-solid fa-star" />
                        <i className="fa-solid fa-star" />
                      </div>
                      <p>
                        Reliability, measured by uptime and consistent performance, is essential to avoid costly disruptions.                      </p>
                      <div className="flex_box">
                        <div className="image_box">
                          <img src="/assets/images/client_img1.png" alt="" />
                        </div>
                        <div className="text_box">
                          <h5>Charlie Low</h5>
                          <p>
                            Business Analyst, <span>Gix Infocom</span>
                          </p>
                        </div>
                      </div>
                      <span className="badge bg-secondary">
                        {" "}
                        4.5 <i className="fa-solid fa-star" />{" "}
                      </span>
                    </div>
                  </div>
                </SwiperSlide>
                <SwiperSlide>
                  <div className="item">
                    <div className="review_box">
                      <div className="star_box">
                        <i className="fa-solid fa-star" />
                        <i className="fa-solid fa-star" />
                        <i className="fa-solid fa-star" />
                        <i className="fa-solid fa-star" />
                        <i className="fa-solid fa-star" />
                      </div>
                      <p>
                        Furthermore, responsive and knowledgeable customer support can make or break the user experience, especially during troubleshooting.
                      </p>
                      <div className="flex_box">
                        <div className="image_box">
                          <img src="" alt="" />
                        </div>
                        <div className="text_box">
                          <h5>Charlie Low</h5>
                          <p>
                            Business Analyst, <span>Gix Infocom</span>
                          </p>
                        </div>
                      </div>
                      <span className="badge bg-secondary">
                        {" "}
                        4.5 <i className="fa-solid fa-star" />{" "}
                      </span>
                    </div>
                  </div>
                </SwiperSlide>
                <SwiperSlide>
                  <div className="item">
                    <div className="review_box">
                      <div className="star_box">
                        <i className="fa-solid fa-star" />
                        <i className="fa-solid fa-star" />
                        <i className="fa-solid fa-star" />
                        <i className="fa-solid fa-star" />
                        <i className="fa-solid fa-star" />
                      </div>
                      <p>
                        Seamless integration with existing business applications and competitive pricing structures are also vital considerations.
                      </p>
                      <div className="flex_box">
                        <div className="image_box">
                          <img src="/assets/images/client_img1.png" alt="" />
                        </div>
                        <div className="text_box">
                          <h5>Charlie Low</h5>
                          <p>
                            Business Analyst, <span>Gix Infocom</span>
                          </p>
                        </div>
                      </div>
                      <span className="badge bg-secondary">
                        {" "}
                        4.5 <i className="fa-solid fa-star" />{" "}
                      </span>
                    </div>
                  </div>
                </SwiperSlide>
                <SwiperSlide>
                  <div className="item">
                    <div className="review_box">
                      <div className="star_box">
                        <i className="fa-solid fa-star" />
                        <i className="fa-solid fa-star" />
                        <i className="fa-solid fa-star" />
                        <i className="fa-solid fa-star" />
                        <i className="fa-solid fa-star" />
                      </div>
                      <p>
                        Ultimately, a well-chosen PBX system should enhance communication, streamline workflows, and provide a solid return on investment.
                      </p>
                      <div className="flex_box">
                        <div className="image_box">
                          <img src="/assets/images/client_img1.png" alt="" />
                        </div>
                        <div className="text_box">
                          <h5>Charlie Low</h5>
                          <p>
                            Business Analyst, <span>Gix Infocom</span>
                          </p>
                        </div>
                      </div>
                      <span className="badge bg-secondary">
                        {" "}
                        4.5 <i className="fa-solid fa-star" />{" "}
                      </span>
                    </div>
                  </div>
                </SwiperSlide>
              </Swiper>
            </div>
          </div>
        </section>
        {/*===End===*/}
        {/*===Mobile Navbar code start===*/}
        <div
          className="offcanvas offcanvas-start"
          tabIndex={-1}
          id="offcanvasExample"
          aria-labelledby="offcanvasExampleLabel"
        >
          <div className="offcanvas-header">
            <button
              type="button"
              className="btn-close text-reset"
              data-bs-dismiss="offcanvas"
              aria-label="Close"
            />
          </div>
          <div className="offcanvas-body">
            <div className="mobile_showcontent">
              <ul>
                <li>
                  <Link href="/">Products</Link>
                </li>
                <li>
                  <Link href="/">Solutions</Link>
                </li>
                <li>
                  <Link href="/">Plans &amp; Pricing</Link>
                </li>
                <li>
                  <Link href="/">Resources</Link>
                </li>
              </ul>
            </div>
          </div>
        </div>
        {/*===End===*/}
        {/*====jquery links====*/}
        {/*====owl slider links====*/}

      </div>
      <footer>
        <div className="col-12">
          <div className="trial_cta">
            <h2>Get started with a 14-day trial</h2>
            <div className="center_box">
              <Link href="#">
                {" "}
                Contact Us <i class="fa-solid ms-2 fa-arrow-right"></i>{" "}
              </Link>
              <Link href="#" className="call_ctn">
                {" "}
                Call Now<i class="fa-solid ms-2 fa-arrow-right"></i>{" "}
              </Link>
            </div>
          </div>
        </div>
      </footer>

    </>
  );
}
